version: '2'
services:
  dizel-web-php73:
    build: docker/php7.3/
    container_name: dizel-app-skeleton
    image: dizel-app-php73
    environment:
      - APP_CONFIG=../config/web.dev.php
      - APP_DEBUG_MODE=true
    command: "bash -c 'cd /app && composer install && php -S 0.0.0.0:9191 -t /app/public'"
    volumes:
      # - .composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      net_citycard:
        ipv4_address: 172.25.0.10
    # ports:
    #   - '9191:9191'

#  dizel-cli-php73:
##    build: docker/php7.3/
##    container_name: dizel-app-skeleton
#    image: dizel-app-php73
#    environment:
#      - APP_CONFIG=../config/cli.dev.php
#      - APP_DEBUG_MODE=true
##    command: "bash -c 'cd /app && composer install && chmod -R 0777 /app/vendor && php -S 0.0.0.0:9191 -t /app/public'"
#    volumes:
#      # - .composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated

networks:
  net_citycard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24