version: '2'
services:
  dizel-web-php73:
    build: docker/php7.3/
    container_name: dizel-app-skeleton
    image: dizel-app-php73
    environment:
      - APP_CONFIG=../config/web.dev.php
      - APP_DEBUG_MODE=true
#    command: "bash -c 'cd /app && composer install && php -S 0.0.0.0:9191 -t /app/public'"
    command: "bash -c 'cd /app && composer install && /usr/sbin/php-fpm7 -F -R'"
    volumes:
      # - .composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php7.3/php-fpm.conf:/etc/php7/php-fpm.d/www.conf
    networks:
      net_citycard:
        ipv4_address: 172.25.0.20

  dizel-web-nginx:
    image: nginx:1.15
    container_name: dizel-app-nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
#      - ../www:/www
#      - ./nginx/nginx.server.conf:/etc/nginx/nginx.conf
#      - ./nginx/common.vhost.conf:/etc/nginx/common.vhost.conf
    ports:
      - "80:80"
    links:
      - dizel-web-php73
#    depends_on:
#      - phpfpm
#    restart: always
    networks:
      net_citycard:
        ipv4_address: 172.25.0.10
    # ports:
    #   - '9191:9191'

#  dizel-cli-php73:
##    build: docker/php7.3/
##    container_name: dizel-app-skeleton
#    image: dizel-app-php73
#    environment:
#      - APP_CONFIG=../config/cli.dev.php
#      - APP_DEBUG_MODE=true
##    command: "bash -c 'cd /app && composer install && chmod -R 0777 /app/vendor && php -S 0.0.0.0:9191 -t /app/public'"
#    volumes:
#      # - .composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated

networks:
  net_citycard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24